name: Check push
on: [ push ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: run ktlintCheck
        run: ./gradlew --continue ktlintCheck
      
      - name: UnitTest
        run: ./gradlew testDebugUnitTest
